### PR TITLE
Add test scenario for unregistering and dangling references

### PR DESCRIPTION
**Pull request by feihujiang**
Signed-off-by: feihujiang jiangfeihu@huawei.com
#6

### CODE REVIEW

**Comment by feihujiang** [comment]
@rbuysse Could you please review this PR? Thanks!

**Comment by vaporos** [comment]
Sorry for the delay on this one; I was fighting some build system issues.

Anyway, it does not appear to pass run_lint:

`./bin/run_lint
./tests/integration/test_all_transactions.py:129:44: E128 continuation line under-indented for visual indent
./tests/integration/test_all_transactions.py:132:33: E128 continuation line under-indented for visual indent
./tests/integration/test_all_transactions.py:135:80: E501 line too long (90 > 79 characters)
./tests/integration/test_all_transactions.py:137:80: E501 line too long (88 > 79 characters)
./tests/integration/test_all_transactions.py:139:80: E501 line too long (81 > 79 characters)
./tests/integration/test_all_transactions.py:141:80: E501 line too long (81 > 79 characters)
./tests/integration/test_all_transactions.py:145:80: E501 line too long (82 > 79 characters)
`

**Comment by feihujiang** [comment]
I ran ./bin/run_lint, and it passed, please take a look.

**Comment by feihujiang** [comment]
I updated this commit.

**Pull request merged**
